"""init schema

Revision ID: cba770d7f617
Revises: 
Create Date: 2026-05-05 13:57:40.342410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba770d7f617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oracles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('required_inputs', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('birth_date', sa.String(length=10), nullable=False),
    sa.Column('birth_time', sa.String(length=5), nullable=True),
    sa.Column('birth_place', sa.String(length=128), nullable=True),
    sa.Column('birth_lat', sa.Float(), nullable=True),
    sa.Column('birth_lon', sa.Float(), nullable=True),
    sa.Column('birth_tz', sa.String(length=64), nullable=True),
    sa.Column('eye_color', sa.String(length=16), nullable=True),
    sa.Column('garden_zone_usda', sa.Integer(), nullable=True),
    sa.Column('garden_region', sa.String(length=128), nullable=True),
    sa.Column('garden_soil', sa.String(length=16), nullable=True),
    sa.Column('garden_sun', sa.String(length=16), nullable=True),
    sa.Column('garden_size_m2', sa.Float(), nullable=True),
    sa.Column('garden_style', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("eye_color IS NULL OR eye_color IN ('blue','grey','green','hazel','brown','dark','amber')", name='ck_persons_eye_color'),
    sa.CheckConstraint("garden_soil IS NULL OR garden_soil IN ('dry','normal','wet')", name='ck_persons_garden_soil'),
    sa.CheckConstraint("garden_sun IS NULL OR garden_sun IN ('sun','part_shade','shade','mixed')", name='ck_persons_garden_sun'),
    sa.CheckConstraint("gender IS NULL OR gender IN ('female','male','other')", name='ck_persons_gender'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_ru', sa.String(length=128), nullable=False),
    sa.Column('name_lat', sa.String(length=128), nullable=True),
    sa.Column('aka', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('min_zone_usda', sa.Integer(), nullable=True),
    sa.Column('max_zone_usda', sa.Integer(), nullable=True),
    sa.Column('shelter_friendly', sa.Integer(), server_default='0', nullable=False),
    sa.Column('height_max_m', sa.Float(), nullable=True),
    sa.Column('width_max_m', sa.Float(), nullable=True),
    sa.Column('growth_speed', sa.String(length=16), nullable=True),
    sa.Column('sun', sa.String(length=32), nullable=True),
    sa.Column('soil_moisture', sa.String(length=16), nullable=True),
    sa.Column('soil_type', sa.String(length=64), nullable=True),
    sa.Column('element', sa.String(length=32), nullable=True),
    sa.Column('gender_energy', sa.String(length=16), nullable=True),
    sa.Column('planet', sa.String(length=32), nullable=True),
    sa.Column('chakra', sa.Integer(), nullable=True),
    sa.Column('bloom_months', sa.JSON(), nullable=True),
    sa.Column('bloom_color', sa.String(length=64), nullable=True),
    sa.Column('autumn_color', sa.String(length=64), nullable=True),
    sa.Column('evergreen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_weed_like', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hierarchy_potential', sa.Integer(), nullable=True),
    sa.Column('availability_ru', sa.String(length=16), nullable=True),
    sa.Column('approx_price_rub', sa.Integer(), nullable=True),
    sa.Column('short_story', sa.Text(), nullable=True),
    sa.Column('long_story', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("availability_ru IS NULL OR availability_ru IN ('easy','medium','rare')", name='ck_plants_availability_ru'),
    sa.CheckConstraint("category IN ('tree','shrub','perennial','annual','grass','fern','vine','water','bulb','succulent','herb')", name='ck_plants_category'),
    sa.CheckConstraint("gender_energy IS NULL OR gender_energy IN ('masculine','feminine','neutral')", name='ck_plants_gender_energy'),
    sa.CheckConstraint("growth_speed IS NULL OR growth_speed IN ('slow','medium','fast')", name='ck_plants_growth_speed'),
    sa.CheckConstraint("soil_moisture IS NULL OR soil_moisture IN ('dry','normal','wet','any')", name='ck_plants_soil_moisture'),
    sa.CheckConstraint("sun IS NULL OR sun IN ('sun','part_shade','shade','sun_or_part_shade','any')", name='ck_plants_sun'),
    sa.CheckConstraint('chakra IS NULL OR chakra BETWEEN 1 AND 7', name='ck_plants_chakra'),
    sa.CheckConstraint('hierarchy_potential IS NULL OR hierarchy_potential BETWEEN 1 AND 5', name='ck_plants_hierarchy_potential'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index('idx_plants_category', ['category'], unique=False)
        batch_op.create_index('idx_plants_slug', ['slug'], unique=False)

    op.create_table('natal_charts',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('sun_sign', sa.String(length=16), nullable=True),
    sa.Column('moon_sign', sa.String(length=16), nullable=True),
    sa.Column('ascendant_sign', sa.String(length=16), nullable=True),
    sa.Column('fire_count', sa.Integer(), nullable=True),
    sa.Column('earth_count', sa.Integer(), nullable=True),
    sa.Column('air_count', sa.Integer(), nullable=True),
    sa.Column('water_count', sa.Integer(), nullable=True),
    sa.Column('full_chart', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('oracle_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oracle_id', sa.String(length=32), nullable=False),
    sa.Column('matcher', sa.JSON(), nullable=False),
    sa.Column('plant_slug', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('reason_for_expert', sa.Text(), nullable=True),
    sa.Column('reason_for_client', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['oracle_id'], ['oracles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_slug'], ['plants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oracle_entries', schema=None) as batch_op:
        batch_op.create_index('idx_oracle_entries_oracle', ['oracle_id'], unique=False)
        batch_op.create_index('idx_oracle_entries_plant', ['plant_slug'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('active_oracles', sa.JSON(), nullable=False),
    sa.Column('raw_pool', sa.JSON(), nullable=False),
    sa.Column('curated_pool', sa.JSON(), nullable=True),
    sa.Column('expert_notes', sa.Text(), nullable=True),
    sa.Column('title_plant_slug', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_plant_slug'], ['plants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index('idx_recommendations_person', ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index('idx_recommendations_person')

    op.drop_table('recommendations')
    with op.batch_alter_table('oracle_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_oracle_entries_plant')
        batch_op.drop_index('idx_oracle_entries_oracle')

    op.drop_table('oracle_entries')
    op.drop_table('natal_charts')
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index('idx_plants_slug')
        batch_op.drop_index('idx_plants_category')

    op.drop_table('plants')
    op.drop_table('persons')
    op.drop_table('oracles')
    # ### end Alembic commands ###
